server:
  port: 9002
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 182.92.96.33:80 #配置nacos地址
management:
  endpoints:
    web:
      exposure:
        include: "*"
